name: Conditions workflow
on: workflow_dispatch
jobs:
  skip-or-run:
    env:
      ACTOR: ${{ github.actor }}
    if: ${{ github.actor == 'ich1zer0' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.ACTOR }}"
